<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="14.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Modules.Records.Application\Modules.Records.Application.csproj" />
    <ProjectReference Include="..\Shared.Infrastructure\Shared.Infrastructure.csproj" />
  </ItemGroup>

</Project>
