namespace Modules.Records.Application.DTOs;

public sealed record NameSnapshotInput(
    string NameType,
    string LastOrBusinessName,
    string? FirstName = null,
    string? MiddleName = null,
    Guid? SexId = null,
    Guid? RaceId = null,
    DateTime? DateOfBirth = null,
    string? DriversLicenseNumber = null,
    Guid? DriversLicenseStateId = null,
    int? HeightInches = null,
    int? WeightLbs = null,
    Guid? HairColorId = null,
    Guid? EyeColorId = null,
    Guid? SuffixId = null,
    string? PlaceOfBirth = null,
    string? FbiNumber = null,
    string? LocalNumber = null,
    string? PrimaryPhone = null,
    string? PrimaryPhoneExtension = null,
    string? WorkPhone = null,
    string? WorkPhoneExtension = null,
    string? OtherPhone = null,
    string? OtherPhoneExtension = null,
    string? SocialSecurityNumber = null,
    bool IsCitizen = false,
    DateTime? DeceasedDate = null,
    NameSnapshotAddressDto? PrimaryAddress = null,
    NameSnapshotAddressDto? SecondaryAddress = null);
